name: bluff
description: A starting point for Dart libraries or applications.
version: 0.1.11
homepage: https://github.com/aloisdeniel/bluff

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  universal_html: ^2.0.8

dev_dependencies:
  extra_pedantic: ^1.5.0
  test: ^1.6.0
